name: 🔥 Firewall Change Request 🔥
description: Submit a change request for firewall changes
title: "[Firewall Change Request]"
labels: "[firewall]"
body:
  - type: input
    id: SystemId
    attributes:
      label: System Id
      description: What is the id of the system you are requesting an opening for?
      placeholder: e.g. XX-2000
    validations:
      required: false
  - type: checkboxes
    id: environment
    attributes:
      label: Environment
      description: What environment are you requesting a change for? You may select more than one.
      options: 
        - label: Dev
        - label: Test
        - label: Prod
  - type: checkboxes
    id: Authentication-Authorization
    attributes:
      label: authentication-authorization
      description: Does the service require authentication and/or authorization?
      options: 
        - label: Authentication
        - label: Authorization
  - type: input
    id: Traffic
    attributes:
      label: Source and Destination
      description: What the source and destination system?
      placeholder: e.g. AKS Cluster X or Foundation network
    validations:
      required: true
  - type: checkboxes
    id: ExposureCheckbox
    attributes:
      label: Exposure
      description: Are you publicly exposing the service as a result of this change?
      options: 
        - label: Yes
        - label: No
