name: 🔥 Firewall Change Request 🔥
description: Submit a change request for firewall changes
title: "[Firewall Change Request]"
labels: "[firewall]"
body:
  - type: markdown
    attributes:
      value: "## Firewall Change Request form"
  - type: markdown
    attrbibutes:
     value: |
      This form should be used whenever making changes to a Network Security Group. The issue can then be linked to a Pull Request that closes the issue.
  - type: input
    id: SystemId
    attributes:
      label: System Id
      description: What is the id of the system you are requesting an opening for?
      placeholder: e.g. XX-2000
    validations:
      required: false
  - type: checkboxes
    id: environment
    attributes:
      label: Environment
      description: What environment are you requesting a change for? You may select more than one.
      options: 
        - label: Dev
        - label: Test
        - label: Prod
  - type: checkboxes
    id: Authentication-Authorization
    attributes:
      label: authentication-authorization
      description: Does the service require authentication and/or authorization?
      options: 
        - label: Authentication
        - label: Authorization
  - type: input
    id: Traffic
    attributes:
      label: Source and Destination
      description: What the source and destination system?
      placeholder: e.g. AKS Cluster X or Foundation network
    validations:
      required: true
  - type: checkboxes
    id: ExposureCheckbox
    attributes:
      label: Exposure
      description: Are you publicly exposing the service as a result of this change?
      options: 
        - label: "Yes"
        - label: "No"
        - label: "Service already has public exposure"
  - type: checkboxes
    id: EncryptionCheckbox
    attributes:
      label: Encryption
      description: Is the traffic allowed encrypted in transit?
      options: 
        - label: "Yes"
        - label: "No"
        - label: Partially
  - type: input
    id: TrafficEncryptionText
    attributes:
      label: Encryption
      description: If No or Partially on the above please elaborate
      placeholder: e.g. no encryption due to compatibility
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Do you want to add any additional information?
      value: |
        additional information about the change
        ..
    validations:
      required: false
